name: Rust CI

on:
  push:

  pull_request:

jobs:
  build_and_test:
    uses: bluk/actions-workflows/.github/workflows/rust-build-test-std-alloc-multi-platform.yml@9e8e7bbd46f4067426d5a6c6c50d49efb701e758
  clippy:
    uses: bluk/actions-workflows/.github/workflows/rust-clippy.yml@9e8e7bbd46f4067426d5a6c6c50d49efb701e758
  rustfmt:
    uses: bluk/actions-workflows/.github/workflows/rust-rustfmt.yml@9e8e7bbd46f4067426d5a6c6c50d49efb701e758
  audit:
    uses: bluk/actions-workflows/.github/workflows/rust-audit.yml@9e8e7bbd46f4067426d5a6c6c50d49efb701e758